# Generated by Django 3.1.2 on 2020-12-16 15:27

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(max_length=500)),
                ('archivo', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage('/home/enzo/Documentos/proyectos/quiz/static'), upload_to='./preguntas_respuestas/')),
            ],
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('idpadre', mptt.fields.TreeForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='preguntas.temas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemasPreguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preguntas.pregunta')),
                ('idtema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preguntas.temas')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=200)),
                ('correctas', models.IntegerField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='preguntas.pregunta')),
            ],
        ),
    ]
