# Generated by Django 3.1.2 on 2020-12-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temas',
            name='level',
        ),
        migrations.RemoveField(
            model_name='temas',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='temas',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='temas',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='temas',
            name='idpadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preguntas.temas'),
        ),
    ]
