# Generated by Django 3.1.2 on 2020-12-18 23:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_auto_20201211_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage('C:\\Users\\trilo\\Django\\quiz\\preguntas_respuestas'), upload_to='preguntas_respuestas'),
        ),
    ]
