# Generated by Django 3.1.2 on 2020-12-16 16:30

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_auto_20201216_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='name',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='parent',
        ),
        migrations.AddField(
            model_name='tema',
            name='padre',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='preguntas.tema'),
        ),
    ]
