# Generated by Django 3.1.2 on 2020-12-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0006_auto_20201216_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='titulo',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tema',
            old_name='padre',
            new_name='parent',
        ),
    ]
